<?php

namespace Mb\EarthCeoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * TaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRepository extends SortableRepository
{
}
